version: "3"
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      mysqli_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "obs_db"
      MYSQL_USER: "php_docker"
      MYSQL_PASSWORD: "password"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306